""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General "
" Automatically detect file types. "
filetype on
syntax enable

" no vi compatibility. "
set nocompatible

" Add recently accessed projects menu (project plugin) "
set viminfo^=\!

" Minibuffer Explorer Settings "
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1
let mapleader=','

" alt+n or alt+p to navigate between entries in QuickFix "
map <silent> <m-p> :cp <cr>
map <silent> <m-n> :cn <cr>

" Enable error files & error jumping. "
set cf

" Yanks go on clipboard instead. "
set clipboard+=unnamed

" Number of things to remember in history. "
set history=256

" Writes on make/shell commands "
set autowrite

" Ruler on "
set ruler

" Line numbers on "
set nu

" Line wrapping off "
set nowrap

" Time to wait after ESC (default causes an annoying delay) "
set timeoutlen=250

" colorscheme vividchalk "
" Uncomment this to set a default theme "

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Formatting "

" Tabs are 2 spaces "
set ts=2

" Backspace over everything in insert mode "
set bs=2

" Tabs under smart indent "
set shiftwidth=2
set nocp incsearch
set cinoptions=:0,p0,t0
set cinwords=if,else,while,do,for,switch,case
set formatoptions=tcqr
set cindent
set autoindent
set smarttab
set expandtab

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Visual "
set nolist

" Show matching brackets. "
set showmatch

" Bracket blinking. "
set mat=5
" set list

" No blinking . "
set novisualbell

" No noise. "
set noerrorbells

" Always show status line. "
set laststatus=2

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'


Plugin 'rking/ag.vim'
Plugin 'myusuf3/numbers.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-rails'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'wincent/command-t'
Plugin 'kien/ctrlp.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'scrooloose/nerdcommenter'
Plugin 'altercation/vim-colors-solarized'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'Valloric/YouCompleteMe'
Plugin 'tpope/vim-endwise'
Plugin 'kchmck/vim-coffee-script'
Plugin 'slim-template/vim-slim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
let hour = strftime("%H")

if 6 <= hour && hour < 18
  set background=dark
else
  set background=light
endif

colorscheme molokai

let g:EasyMotion_do_mapping = 0 " Disable default mappings

" Bi-directional find motion
" Jump to anywhere you want with minimal keystrokes, with just one key binding.
" `s{char}{label}`
nmap s <Plug>(easymotion-s)
" or
" `s{char}{char}{label}`
" Need one more keystroke, but on average, it may be more comfortable.
nmap s <Plug>(easymotion-s2)

" Turn on case sensitive feature
let g:EasyMotion_smartcase = 1

" JK motions: Line motions
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)

" move code up and down
nnoremap <D-j> :m .+1<CR>==
nnoremap <D-k> :m .-2<CR>==
inoremap <D-j> <Esc>:m .+1<CR>==gi
inoremap <D-k> <Esc>:m .-2<CR>==gi
vnoremap <D-j> :m '>+1<CR>gv=gv
vnoremap <D-k> :m '<-2<CR>gv=gv

set noswapfile
